### ISSUE TITLE
How do I go about installing this?

### ISSUE THREAD

**Issue by EvaIsAdorable** [fblah/ShapeKeyTransferBlender#2]
Hey, I'm sort of a newbie to blender, so pardon me if I'm asking idiotic questions.
But how do I install this particular add-on? I tried zipping it, and installing it as an add-on in user prefs, but it came back with nothing. I think. Please advise. Thanks

**Comment by fblah** [comment]
Download the zip

Goto Edit -> Preferences -> Add-ons

Click Install... and browse to the zip and install it

Search for the Shape Key Transfer addon in the list enable it.

Now when you are in the viewport (under layout) there is a new Tools menu on the right of the viewport. Press N to expand the toolbar...

![image](https://user-images.githubusercontent.com/8712033/151746947-4b29f162-97a7-4ba6-b310-c08a807a3eaf.png)

**Comment by EvaIsAdorable** [comment]
Oh, hey, lookie that. It's been installed this whole time.
But now I know where to find it.
Thanks for getting back to me, and being patient. Really appreciate it
